version: "3.8"

services:
  postgres:
    image: postgres:14
    container_name: chat-app
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: chat-app
    networks:
      - devNetwork

networks:
  devNetwork: